module.exports = {
  purge: [],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "brand-light-blue": "#9cdcfe",
        "brand-dark-blue": "#005b99",
        "brand-darker-blue": "#1a202c",
        "dark-gray": "#2e353f",
        "light-azure": "#d1dce5",
        "sapphire-white": "#d5dae6",
      },
      fontFamily: {
        sans: [
          "Montserrat",
          "ui-sans-serif",
          "system-ui",
          "-apple-system",
          "BlinkMacSystemFont",
          '"Segoe UI"',
          "Roboto",
          '"Helvetica Neue"',
          "Arial",
          '"Noto Sans"',
          "sans-serif",
          '"Apple Color Emoji"',
          '"Segoe UI Emoji"',
          '"Segoe UI Symbol"',
          '"Noto Color Emoji"',
        ],
        serif: [
          "Merriweather",
          "ui-serif",
          "Georgia",
          "Cambria",
          '"Times New Roman"',
          "Times",
          "serif",
        ],
      },
    },
  },
  variants: {
    extend: {
      accessibility: ["dark"],
      alignContent: ["dark"],
      alignItems: ["dark"],
      alignSelf: ["dark"],
      animation: ["dark"],
      appearance: ["dark"],
      backgroundAttachment: ["dark"],
      backgroundClip: ["dark"],
      backgroundColor: ["dark"],
      backgroundImage: ["dark"],
      backgroundOpacity: ["dark"],
      backgroundPosition: ["dark"],
      backgroundRepeat: ["dark"],
      backgroundSize: ["dark"],
      borderCollapse: ["dark"],
      borderColor: ["dark"],
      borderOpacity: ["dark"],
      borderRadius: ["dark"],
      borderStyle: ["dark"],
      borderWidth: ["dark"],
      boxShadow: ["dark"],
      boxSizing: ["dark"],
      clear: ["dark"],
      container: ["dark"],
      cursor: ["dark"],
      display: ["dark"],
      divideColor: ["dark"],
      divideOpacity: ["dark"],
      divideStyle: ["dark"],
      divideWidth: ["dark"],
      fill: ["dark"],
      flex: ["dark"],
      flexDirection: ["dark"],
      flexGrow: ["dark"],
      flexShrink: ["dark"],
      flexWrap: ["dark"],
      float: ["dark"],
      fontFamily: ["dark"],
      fontSize: ["dark"],
      fontSmoothing: ["dark"],
      fontStyle: ["dark"],
      fontVariantNumeric: ["dark"],
      fontWeight: ["dark"],
      gap: ["dark"],
      gradientColorStops: ["dark"],
      gridAutoColumns: ["dark"],
      gridAutoFlow: ["dark"],
      gridAutoRows: ["dark"],
      gridColumn: ["dark"],
      gridColumnEnd: ["dark"],
      gridColumnStart: ["dark"],
      gridRow: ["dark"],
      gridRowEnd: ["dark"],
      gridRowStart: ["dark"],
      gridTemplateColumns: ["dark"],
      gridTemplateRows: ["dark"],
      height: ["dark"],
      inset: ["dark"],
      justifyContent: ["dark"],
      justifyItems: ["dark"],
      justifySelf: ["dark"],
      letterSpacing: ["dark"],
      lineHeight: ["dark"],
      listStylePosition: ["dark"],
      listStyleType: ["dark"],
      margin: ["dark"],
      maxHeight: ["dark"],
      maxWidth: ["dark"],
      minHeight: ["dark"],
      minWidth: ["dark"],
      objectFit: ["dark"],
      objectPosition: ["dark"],
      opacity: ["dark"],
      order: ["dark"],
      outline: ["dark"],
      overflow: ["dark"],
      overscrollBehavior: ["dark"],
      padding: ["dark"],
      placeContent: ["dark"],
      placeItems: ["dark"],
      placeSelf: ["dark"],
      placeholderColor: ["dark"],
      placeholderOpacity: ["dark"],
      pointerEvents: ["dark"],
      position: ["dark"],
      resize: ["dark"],
      ringColor: ["dark"],
      ringOffsetColor: ["dark"],
      ringOffsetWidth: ["dark"],
      ringOpacity: ["dark"],
      ringWidth: ["dark"],
      rotate: ["dark"],
      scale: ["dark"],
      skew: ["dark"],
      space: ["dark"],
      stroke: ["dark"],
      strokeWidth: ["dark"],
      tableLayout: ["dark"],
      textAlign: ["dark"],
      textColor: ["dark"],
      textDecoration: ["dark"],
      textOpacity: ["dark"],
      textOverflow: ["dark"],
      textTransform: ["dark"],
      transform: ["dark"],
      transformOrigin: ["dark"],
      transitionDelay: ["dark"],
      transitionDuration: ["dark"],
      transitionProperty: ["dark"],
      transitionTimingFunction: ["dark"],
      translate: ["dark"],
      userSelect: ["dark"],
      verticalAlign: ["dark"],
      visibility: ["dark"],
      whitespace: ["dark"],
      width: ["dark"],
      wordBreak: ["dark"],
      zIndex: ["dark"],
    },
  },
  plugins: [],
}
