import { InferGetStaticPropsType } from "next";
import Head from "next/head";
import React from "react";
import { getHomeStaticProps } from "../../../static/getHomeStaticProps";
import { Footer } from "../../atoms/Footer";
import { Bio } from "../../molecules/Bio";
import { Header } from "../../molecules/Header";
import styles from "./index.module.css";

export const Home = ({
  posts,
}: InferGetStaticPropsType<typeof getHomeStaticProps>) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header title="beraliv" path="home" />

      <main className={styles.main}>
        <div className={styles.bio}>
          <Bio />
        </div>

        <div className={styles.grid}>
          {posts.map(({ description, slug, title }) => (
            <a href={slug} key={slug} className={styles.card}>
              <h2>{title}</h2>
              <p>{description}</p>
            </a>
          ))}
        </div>
      </main>

      <Footer />
    </div>
  );
};
