name: CI

on: push

jobs:
  checks:
    name: Type check
    needs: [install]
    timeout-minutes: 5
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [blog2]
    steps:
      - name: Checkout to current branch
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Cache files
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.9.0

      - name: Install dependencies
        run: pnpm install
        shell: bash

      - name: Type check
        run: pnpm --filter ${{ matrix.package }} run type

      - name: Unit tests
        run: pnpm --filter ${{ matrix.package }} run test:unit
