name: ci

on: push

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - uses: actions/checkout@v2
        with:
          fetch-depth: 100
      - run: git --version
      - run: git fetch origin main --depth=100
      - run: git fetch origin ${{ github.ref }} --depth=100
      - run: git diff origin/main...HEAD --name-only
      - run: yarn install --network-timeout 1000000
  # 🕑 5 seconds
  test_blog:
    name: test blog
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - run: yarn test:blog
  # 🕑 <1 second
  test_blog2:
    name: test blog2
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - run: yarn test:blog2
  # 🕑 15 seconds
  build_blog2:
    name: build blog2
    needs: test_blog2
    runs-on: ubuntu-latest
    steps:
      - run: yarn build:blog2

