name: codegen

on: push

jobs:
  test:
    name: blog
    timeout-minutes: 2
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - uses: actions/checkout@v2
        with:
          fetch-depth: 100
      - run: git --version
      - run: git fetch origin main --depth=100
      - run: git fetch origin ${{ github.ref }} --depth=100
      - run: git diff origin/main...HEAD --name-only
      - run: yarn install --network-timeout 1000000
      - run: yarn dev:blog & sleep 30 && yarn workspace blog codegen
