name: "size"

on: push

jobs:
  bundle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 6.29.1
      - run: pnpm install
      - name: Build
        run: pnpm --filter blog2 run build
      - name: Check bundle sizes
        run: pnpm --filter blog2 run size
        env:
            BUNDLEWATCH_GITHUB_TOKEN: ${{ secrets.BUNDLEWATCH_GITHUB_TOKEN }}
