name: "size"

on:
  pull_request:
    branches:
      - main
jobs:
  bundle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: pnpm --filter blog2 run build
      - name: Check bundle sizes
        run: pnpm --filter blog2 run size
        env:
            BUNDLEWATCH_GITHUB_TOKEN: ${{ secrets.BUNDLEWATCH_GITHUB_TOKEN }}
